"""SQLAlchemy implementation of ``IncidentRepository`` (ADR-001, ADR-002)."""

from __future__ import annotations

from uuid import UUID

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.orm import selectinload

from aegis.core.protocols import IncidentFilters
from aegis.domain.incidents.entity import Incident
from aegis.domain.incidents.enums import IncidentState
from aegis.infrastructure.database.models.incident import IncidentModel
from aegis.infrastructure.repositories.mappers import apply_to_orm, to_domain, to_orm
from aegis.shared.exceptions import NotFoundError


class SqlAlchemyIncidentRepository:
    def __init__(self, session: AsyncSession) -> None:
        self._session = session

    # This method ('create') is using SQLAlchemy ORM to store data in the database.
    # Specifically, it takes a domain Incident object, maps it to its ORM (database model) representation,
    # adds it to the SQLAlchemy session, flushes pending changes (to get autogenerated fields like PKs),
    # refreshes the object to reflect latest DB state (e.g., after triggers), 
    # and returns the new Incident as a domain object.
    async def create(self, incident: Incident) -> Incident:
        row = to_orm(incident)                # Convert to ORM/db model
        self._session.add(row)                # Add to session (marks for INSERT)
        await self._session.flush()           # Flush to DB, assign PKs, etc.
        await self._session.refresh(row, attribute_names=["state_history"])  # Reload updated fields
        return to_domain(row)                 # Convert back to domain entity

    # General ways to store data in any DB:
    # 1. ORM (Object-Relational Mapping): Using libraries like SQLAlchemy (Python), Hibernate (Java), or Entity Framework (.NET).
    #    Pros: Easier and more Pythonic code, domain-model-focused, auto-mappings, change tracking.
    #    Cons: Less control over raw SQL, can be slower for complex queries/operations, possible N+1 issues if not careful.
    # 2. Direct SQL (Raw Queries): Writing SQL INSERT/UPDATE/DELETE statements directly.
    #    Pros: Full control, potentially most efficient, can use DB-specific features and optimizations.
    #    Cons: Harder to maintain, more error-prone, less abstraction, risk of SQL injection if not parameterized.
    # 3. Query Builders: Tools/libraries that construct SQL queries programmatically (e.g., SQLAlchemy Core, Knex.js).
    #    Pros: Balance between control and safety, often less boilerplate than raw SQL, protects against injection.
    #    Cons: Extra learning curve, not always as concise as ORM for simple cases.
    # 4. Stored Procedures/Triggers: Define business logic at the DB layer; app invokes procedure or triggers fire on data change.
    #    Pros: Centralized, can optimize at DB-level, atomic operations.
    #    Cons: Logic split between code and DB, harder to test/migrate/version, DB lock-in.

    # Most effective method?
    # - For simple CRUD and domain-driven apps: ORMs are very productive, especially for rapid development, abstraction, and maintainability.
    # - For heavy batch operations, performance-critical workloads, or need for advanced SQL: raw SQL or query builders may perform better.
    # - For logic that's best kept within DB boundaries (auditing, cascading changes): stored procedures/triggers.

    # In modern teams, often a hybrid approach is best: 
    # use ORM for general persistence, but drop to raw SQL or SPs for critical paths.

    async def get_by_id(self, id: UUID) -> Incident | None:
        row = await self._load(id)
        if row is None:
            return None
        return to_domain(row)

    async def list(self, filters: IncidentFilters) -> list[Incident]:
        stmt = (
            select(IncidentModel)
            .options(selectinload(IncidentModel.state_history))
            .where(IncidentModel.deleted_at.is_(None))
            .order_by(IncidentModel.created_at.desc())
        )
        if filters.state is not None:
            stmt = stmt.where(IncidentModel.state == filters.state.value)
        if filters.severity is not None:
            stmt = stmt.where(IncidentModel.severity == filters.severity.value)
        if filters.affected_service is not None:
            stmt = stmt.where(IncidentModel.affected_service == filters.affected_service)
        if filters.owner_id is not None:
            stmt = stmt.where(IncidentModel.owner_id == filters.owner_id)
        if filters.created_after is not None:
            stmt = stmt.where(IncidentModel.created_at >= filters.created_after)
        if filters.created_before is not None:
            stmt = stmt.where(IncidentModel.created_at <= filters.created_before)

        result = await self._session.execute(stmt)
        return [to_domain(row) for row in result.scalars().unique().all()]

    async def save(self, incident: Incident) -> Incident:
        row = await self._load(incident.id)
        if row is None:
            raise NotFoundError(f"Incident '{incident.id}' was not found.")
        apply_to_orm(incident, row)
        await self._session.flush()
        await self._session.refresh(row, attribute_names=["state_history"])
        return to_domain(row)

    async def _load(self, incident_id: UUID) -> IncidentModel | None:
        stmt = (
            select(IncidentModel)
            .options(selectinload(IncidentModel.state_history))
            .where(
                IncidentModel.id == incident_id,
                IncidentModel.deleted_at.is_(None),
            )
        )
        result = await self._session.execute(stmt)
        return result.scalar_one_or_none()

    async def get_open_by_fingerprint(self, fingerprint: str) -> Incident | None:
        stmt = (
            select(IncidentModel)
            .options(selectinload(IncidentModel.state_history))
            .where(
                IncidentModel.fingerprint == fingerprint,
                IncidentModel.state == IncidentState.OPEN.value,
                IncidentModel.deleted_at.is_(None),
            )
            .limit(1)
        )
        result = await self._session.execute(stmt)
        row = result.scalar_one_or_none()
        return None if row is None else to_domain(row)
